%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('ResponseType', {anyAttribs, 'Errors'}).
-record('ErrorsType', {anyAttribs, 'Error'}).
-record('ErrorType', {anyAttribs, 'Code', 'Message'}).
