%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('EC2ErrorResponseType', {anyAttribs, 'Errors', 'RequestID'}).
-record('EC2ErrorsType', {anyAttribs, 'Error'}).
-record('EC2ErrorType', {anyAttribs, 'Code', 'Message'}).
